export const LOGIN_REQUEST = "lOGIN_REQUEST";
export const LOGIN_SUCCESS = "lOGIN_SUCCESS";
export const LOGIN_FAIL = "lOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTERSUCCESSL";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOADSUCCESSL";
export const LOAD_FAIL = "LOAD_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
