export const GET_MOVIE_DETAIL_REQUEST = "GET_MOVIE_DETAIL_REQUEST";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAIL = "GET_MOVIE_DETAIL_FAIL";

export const FAV_MOV_REQUEST = "FAV_MOV_REQUEST";
export const FAV_MOV_SUCCESS = "FAV_MOV_SUCCESS";
export const FAV_MOV_FAIL = "FAV_MOV_FAIL";

export const LOAD_FAV_REQUEST = "LOAD_FAV_REQUEST";
export const LOAD_FAV_SUCCESS = "LOAD_FAV_SUCCESS";
export const LOAD_FAV_FAIL = "LOAD_FAV_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
